= Step 5. estimate_loss()

[source,python,linenums]
----
include::example$gpt.py[lines=50..62]
----


- Das Modell wird zunächst in den Evaluierungsmodus gesetzt (`model.eval()`), was bedeutet, dass spezifische Verhaltensweisen wie Dropout deaktiviert werden.
- Für jeden Datensplit (`'train'`, `'val'`) wird eine Reihe von Verlustwerten gesammelt, indem für jede Iteration (`eval_iters`) ein Datenbatch geholt, durch das Modell geführt und der Verlust berechnet wird.
- Der Verlust wird von der modifizierten `forward`-Methode des Modells zurückgegeben, welche die Logits und den Verlust auf Basis der Eingangsdaten `X` und der tatsächlichen Etiketten `Y` berechnet.
- Am Ende wird das Modell wieder in den Trainingsmodus (`model.train()`) versetzt.

Dieses Muster erlaubt eine flexible Nutzung des Modells sowohl für Vorhersagen als auch für die Verlustberechnung, je nach den übergebenen Argumenten.


== Batch & Block explanation
[source,python]
----
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")
----

[source,text]
----
when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58

----

== get batch Code
[source,python,linenums]
----
include::example$gpt.py[lines=41..48]
----
